### Get products
GET http://localhost:8085/api/v2/stock/product HTTP/1.1


### Get product by Id
GET http://localhost:8085/api/v2/stock/product/7 HTTP/1.1


### Get product by keyword
GET http://localhost:8085/api/v2/stock/product/keyword/Arduino Nano HTTP/1.1


### Create 
POST http://localhost:8085/api/v2/stock/product HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Angular 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

3000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

1800
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Update 
PUT http://localhost:8085/api/v2/stock/product HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id";

39
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

React 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

111
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

222
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test2.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Delete 
DELETE http://localhost:8085/api/v2/stock/product/13 HTTP/1.1